---
- name: "PLAY 1: Configure All Lan Switches"
  hosts: lan
  tags: lan
  connection: network_cli
  gather_facts: no
  collections:
    - cisco.ios
  tasks:
    - name: "P1T1: Configure Hostname and Domain Name"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"
    - name: Merge provided configuration with device configuration
      ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            trunk:
              allowed_vlans: "{{ vlans | map(attribute='vlan_id') | join(',') }}"
#              native_vlan: 20
#              pruning_vlan: 10,20
              encapsulation: dot1q
#              - allowed_vlan: "{{ vlans | map(attribute='vlan_id') | join(',') }}"
#                 native_vlan: 1
#                 encapsulation: dot1q
        state: merged
      loop: "{{ interfaces[inventory_hostname] | selectattr('mode','equalto','trunk') | list }}"

    - name: "P1T2: Configure NTP"
      ios_ntp:
        server: "{{ ntp_server }}"
        logging: true
        state: present
