- name: "PLAY 3: Configure WAN Routers"
  hosts: wan
  tags: wan
  tasks:
    - name: "P3T1: Configure System parameters"
      ios_system:
        hostname: "{{ inventory_hostname }}"
        domain_name: "{{ domain_name }}"
        lookup_enabled: no
        name_servers: "{{ name_servers }}"

    - name: "P3T2: Configure NTP"
      ios_ntp:
        server: "{{ ntp_server }}"
        logging: true
        source_int: GigabitEthernet0/2
        state: present




 #   - name: "P3T2: Configure Managment Static Routes"
 #     ios_static_routes:
 #       config:
 #       - address_families:
 #         - afi: ipv4
 #         routes:
 #         - dest: "{{ item.prefix.split('/')[0] }}""{{ item.prefix | ipv4('netmask') }}"
 #       prefix: "{{ item.prefix.split('/')[0] }}"
 #       mask: "{{ item.prefix | ipv4('netmask') }}"
 #         next_hops: "{{ item.next_hop }}"
 #     loop: "{{ mgmt_static_routes }}"
    - name: "P3T3: Configure All Interfaces"
      cisco.ios.ios_interfaces:
        config:
        - name: "{{ item.name }}"
          description: "{{ item.description | default('') }}"
#          mtu: "{{ intf_mtu }}"
          enabled: true
        state: merged
      loop: "{{ wan_l3_links[inventory_hostname] }}"

#  - name: "P3T3: Configure All Interfaces"
#    ios_interface:
#      name: "{{ item.name }}"
#      description: "{{ item.description | default('') }}"
#      mtu: "{{ intf_mtu }}"
#      state: up
#    loop: "{{ wan_l3_links[inventory_hostname] }}"

    - name: "P2T1: Create L3 VLAN Interfaces"
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "{{item.name }}"
          ipv4:
          - address: "{{item.ipv4}}"
        state: merged
      loop: "{{wan_l3_links[inventory_hostname]}}"


#  - name: "P3T4: Configure Interface IP Addresses"
#    ios_l3_interface:
#      name: "{{item.name }}"
#      ipv4:  "{{item.ipv4 }}"
#    loop: "{{wan_l3_links[inventory_hostname]}}"


    - name: "P3T5: Configure OSPF"
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines:
          - router-id {{ loopback_prefix | ipv4(hst_router_id) | ipaddr('address')}}

    - name: "P3T6: Configure OSPF On Interfaces"
      ios_config:
        parents: interface {{ item.name }}
        lines:
          - ip ospf {{ ospf_process }} area {{ ospf_area }}
          - ip ospf network point-to-point
          - ip ospf cost {{item.ospf_metric | default(ospf_metric)}}
      loop: "{{ wan_l3_links[inventory_hostname] | selectattr('ospf') | list  }}"

    - name: "P3T7: Configure OSPF Passive Interfaces"
      ios_config:
        parents: router ospf {{ ospf_process }}
        lines: passive-interface {{item.name}}
        save_when: changed
      loop: "{{ wan_l3_links[inventory_hostname] | selectattr('ospf','equalto','passive') | list }}"

