---
- name: "PLAY 1: Configure All Lan Switches"
  hosts: all
  connection: network_cli
  gather_facts: no
  collections:
    - cisco.ios
  tasks:
    - name: "P1T1: Configure Hostname and Domain Name"
      ios_system:
        hostname: git
        domain_name: git.fr
        lookup_enabled: no
        name_servers: 8.8.8.8
