---
- name: Populate NetBox DataBase
  hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: local
    netbox_state: present
    validate_certs: no
  tasks:
    - import_role: 
        name: build_netbox_db
