---
- name: Create Report from Netbox Data
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Build Report
      blockinfile:
        block: |
            netbox_data:
            {% for node in ansible_play_hosts %}
                {% set mgmt_ip = "" %}
                {% for interfaces in hostvars[node].interfaces if interfaces.mgmt_only %}
                    {% set mgmt_ip = interfaces.ip_addresses[0].address %}
                {% endfor %}
                { node: {{ node }}, type: {{ hostvars[node].device_types[0] }}, mgmt_ip: {{ mgmt_ip }} }
            {% endfor %}
        path: ./netbox_report.yaml
        create: yes
      delegate_to: localhost
      run_once: yes

#- name: Output Spine Nodes
#  hosts: device_roles_Spine_Switch
#  gather_facts: no
#  connection: local
#  tasks:
#    - debug: var=inventory_hostname
#      delegate_to: localhost
