---
- name: Build Juniper SP Network
  hosts: junos
  tasks:
    - name: "Enable NETCONF"
      junos_netconf:
        netconf_port: 830
        state: present
      vars:
        ansible_connection: network_cli
      tags: netconf

    - name: Build Device Configuration 
      import_role:
        name: build_router_config
      vars:
          ansible_connection: local
      tags: build
